spring.application.name=mind-track-api
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/mindtrack_db
spring.datasource.username=postgres
spring.datasource.password=Candelaria97
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.jwt.secret=mindtrack-super-secret-key-2024-psychology-app
app.jwt.expiration=86400000
